dependencies:
  - aave/protocol-v2@1.0.1
compiler:
  solc:
    remappings:
      - "@aave=aave/protocol-v2@1.0.1"
dotenv: .env
networks:
  sepolia:
    weth_token: "0xfff9976782d46cc05630d1f6ebab18b2324d6b14"
  mainnet-fork:
    weth_token: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
wallets:
  from_key: ${PRIVATE_KEY}
